# Generated by Django 3.1.6 on 2021-02-21 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='added',
            new_name='addedTimestamp',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='SDID',
            new_name='device_id',
        ),
        migrations.RenameField(
            model_name='userconfigurations',
            old_name='overview',
            new_name='measurements',
        ),
        migrations.CreateModel(
            name='MobileTokenSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('createdTimestamp', models.DateTimeField(auto_now=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
